spring.application.name=TicketingSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing
spring.datasource.username=postgres
spring.datasource.password=9587152404

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mkxOSmgGbkHRYLEhUr6azmwQ5oin6fa0fAs3rTWxMZVBdIjZVRxH9akPsuciPaY2/Xj99a3JGZGcz9S7ib4Liw==
jwt.expiration-ms=86400000