package com.Chrianto.TicketingSystem.entity.enums;

public enum IncidentAction {
    REPORTED,
    CLOSED,
    REOPENED,
    INFO_CHANGED,
    COMMENT_ADDED,
    COMMENT_EDITED,
    COMMENT_REMOVED,
    ATTACHMENT_ADDED,
    ATTACHMENT_REMOVED,
    TICKET_ASSIGNED,
    TICKET_RESOLVED,
    TICKET_CANCELLED,
    TICKET_REOPENED
}
