-- Baseline snapshot of the schema as it existed before Flyway was introduced
-- (previously managed by Hibernate's ddl-auto=update). On the pre-existing dev
-- database this version is marked as applied without running (see
-- spring.flyway.baseline-on-migrate in application.properties); a fresh/empty
-- database runs it like any other migration.

CREATE TABLE public.attachment (
    id bigint NOT NULL,
    content_type character varying(255),
    file_name character varying(255) NOT NULL,
    file_path character varying(255) NOT NULL,
    file_size bigint,
    uploaded_at timestamp(6) without time zone,
    uploaded_by_id bigint,
    ticket_id bigint NOT NULL
);

ALTER TABLE public.attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.category (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    sort_order integer
);

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.comment (
    id bigint NOT NULL,
    text character varying(3000),
    "timestamp" timestamp(6) without time zone,
    ticket_id bigint,
    author_id bigint
);

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.department (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    g_code character varying(255)
);

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.incident_report (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(2000),
    updated_at timestamp(6) without time zone,
    creator_id bigint,
    status character varying(255),
    CONSTRAINT incident_report_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'RESOLVED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.incident_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.problem_category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.problem_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.problem_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subcategory (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    category_id bigint NOT NULL,
    sort_order integer
);

ALTER TABLE public.subcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ticket (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(2000),
    ip_address character varying(255),
    phone_number character varying(255),
    priority character varying(255),
    status character varying(255),
    updated_at timestamp(6) without time zone,
    assigned_user_id bigint,
    creator_id bigint,
    department_id bigint,
    last_modified_id bigint,
    caller_name character varying(255),
    category_id bigint,
    subcategory_id bigint,
    details character varying(2000),
    resolution character varying(2000),
    CONSTRAINT ticket_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT ticket_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'RESOLVED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ticket_history (
    id bigint NOT NULL,
    action character varying(255),
    "timestamp" timestamp(6) without time zone,
    assigned_to_id bigint,
    comment_id bigint,
    performed_by_id bigint,
    ticket_id bigint,
    CONSTRAINT ticket_history_action_check CHECK (((action)::text = ANY (ARRAY['CREATED'::text, 'ASSIGNED'::text, 'REASSIGNED'::text, 'RESOLVED'::text, 'CANCELLED'::text, 'PRIORITY_CHANGED'::text, 'COMMENT_ADDED'::text, 'REOPENED'::text])))
);

ALTER TABLE public.ticket_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    phone_number character varying(255),
    is_active boolean DEFAULT true NOT NULL,
    scheduled_deletion_at timestamp(6) without time zone,
    first_name character varying(255),
    last_name character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.incident_report
    ADD CONSTRAINT incident_report_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.problem_category
    ADD CONSTRAINT problem_category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subcategory
    ADD CONSTRAINT subcategory_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT ticket_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.department
    ADD CONSTRAINT uk1t68827l97cwyxo9r1u6t4p7d UNIQUE (name);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uk46ccwnsi9409t36lurvtyljak UNIQUE (name);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT ukb5uiuh8h4yx0pa1bs86u7jhr UNIQUE (comment_id);

ALTER TABLE ONLY public.problem_category
    ADD CONSTRAINT ukn4emogrdfvplh2trtiqi51lwt UNIQUE (name);

ALTER TABLE ONLY public.subcategory
    ADD CONSTRAINT ukn6aua0mn6urkkayhtandamwxu UNIQUE (category_id, name);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fk3g2gmlm6p2o4hc5oggcvq51x3 FOREIGN KEY (category_id) REFERENCES public.category(id);

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT fk4mcokml4p07tvgif5udmat6cj FOREIGN KEY (performed_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.subcategory
    ADD CONSTRAINT fke4hdbsmrx9bs9gpj1fh4mg0ku FOREIGN KEY (category_id) REFERENCES public.category(id);

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT fkedqxly6v2mkdjt67ujfn47qh9 FOREIGN KEY (ticket_id) REFERENCES public.ticket(id);

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT fkgxo6vne5yymnl72hcp765kses FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkh33hi5t6a64q5nq9n0kwoa8to FOREIGN KEY (department_id) REFERENCES public.department(id);

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkhqv10sa9dlk1a227n9u45atgj FOREIGN KEY (assigned_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT fkik593n7nw26gtpeifbpd0lxcq FOREIGN KEY (assigned_to_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fkir20vhrx08eh4itgpbfxip0s1 FOREIGN KEY (author_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT fklr14j01wxluvddh2405xrkwxt FOREIGN KEY (comment_id) REFERENCES public.comment(id);

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkls47je3cbr91ofovjrkc34adq FOREIGN KEY (creator_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.ticket_history
    ADD CONSTRAINT fkn172ccrihn09prjnpoyxabcgw FOREIGN KEY (ticket_id) REFERENCES public.ticket(id);

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fknq4jpu6xjrpyoipvdmeuv54bv FOREIGN KEY (subcategory_id) REFERENCES public.subcategory(id);

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fko687ip3fmgyb0y4q7slkgcne1 FOREIGN KEY (last_modified_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fksyf8wt2qb7rhcau6v3p4axrba FOREIGN KEY (ticket_id) REFERENCES public.ticket(id);

ALTER TABLE ONLY public.incident_report
    ADD CONSTRAINT fkv23ccgq8g6o8qosyg8xcvtg6 FOREIGN KEY (creator_id) REFERENCES public.users(id);
