-- Re-enables the IncidentReport feature's entity mappings (Attachment.incidentReport,
-- Comment.incidentReport, Ticket.incidentReport, Ticket.source), which were reinstated
-- in the Java entities without a matching schema change. Adds the columns Hibernate's
-- ddl-auto=validate was failing to find.
--
-- This database was baselined rather than built from V1 (see
-- spring.flyway.baseline-on-migrate) — V1's text is a historical snapshot that was
-- never actually executed here, so it documents a schema this live database doesn't
-- necessarily match. incident_report is a case in point: V1 describes it, but it
-- doesn't actually exist on this database (presumably dropped when the feature was
-- finalized out), so it's (re)created defensively here instead of assumed present.
CREATE TABLE IF NOT EXISTS public.incident_report (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(2000),
    updated_at timestamp(6) without time zone,
    creator_id bigint,
    status character varying(255),
    CONSTRAINT incident_report_pkey PRIMARY KEY (id),
    CONSTRAINT incident_report_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'RESOLVED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT fk_incident_report_creator FOREIGN KEY (creator_id) REFERENCES public.users(id)
);

ALTER TABLE public.incident_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incident_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.attachment ADD COLUMN IF NOT EXISTS incident_report_id bigint;
ALTER TABLE public.attachment ALTER COLUMN ticket_id DROP NOT NULL;

ALTER TABLE public.comment ADD COLUMN IF NOT EXISTS incident_report_id bigint;

ALTER TABLE public.ticket ADD COLUMN IF NOT EXISTS incident_report_id bigint;

-- Ticket.source is @Column(nullable = false); every existing ticket predates the
-- INCIDENT source, so backfill to MANUAL before tightening the constraint.
ALTER TABLE public.ticket ADD COLUMN IF NOT EXISTS source character varying(255);
UPDATE public.ticket SET source = 'MANUAL' WHERE source IS NULL;
ALTER TABLE public.ticket ALTER COLUMN source SET NOT NULL;
ALTER TABLE public.ticket DROP CONSTRAINT IF EXISTS ticket_source_check;
ALTER TABLE public.ticket ADD CONSTRAINT ticket_source_check
    CHECK (((source)::text = ANY ((ARRAY['MANUAL'::character varying, 'INCIDENT'::character varying])::text[])));

ALTER TABLE public.attachment
    ADD CONSTRAINT fk_attachment_incident_report FOREIGN KEY (incident_report_id) REFERENCES public.incident_report(id);

ALTER TABLE public.comment
    ADD CONSTRAINT fk_comment_incident_report FOREIGN KEY (incident_report_id) REFERENCES public.incident_report(id);

ALTER TABLE public.ticket
    ADD CONSTRAINT fk_ticket_incident_report FOREIGN KEY (incident_report_id) REFERENCES public.incident_report(id);
